version: "3.9"
services:
    nexus:
        container_name: nexus
        image: sonatype/nexus3
        ports:
            - 8081:8081
            - 8082:8082
        volumes:
            - nexus:/nexus-data

volumes:
    nexus:
